version: '3'

services: 

  app:
    container_name: app
    build: ./node
    volumes: 
      - ./node:/usr/src/app
    depends_on: 
      - db
    networks: 
      - node-network

  db:
    container_name: db
    build: ./mysql
    volumes: 
      - ./dbdata:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network
  
  nginx: 
    container_name: pfa-nginx
    build: ./nginx
    ports: 
      - 8080:80
    depends_on: 
      - app
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge   